# Generated by Django 4.2.6 on 2023-10-11 14:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Sweets'), ('2', 'Breakfast'), ('3', 'Lunch'), ('4', 'Dinner'), ('5', 'Snack')], max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.JSONField()),
                ('cooking_time', models.PositiveIntegerField(default=1)),
                ('number_of_portions', models.SmallIntegerField(default=1)),
                ('recipe_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipetype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
